# Generated by Django 4.0.2 on 2022-05-04 09:50

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_store_book_documen_844838_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='document',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
