# Generated by Django 4.0.2 on 2022-05-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_store_book_documen_844838_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
