# Generated by Django 4.0.2 on 2022-05-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_store_book_documen_844838_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to='covers'),
        ),
    ]
