# Generated by Django 4.0.2 on 2022-05-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
