# Generated by Django 4.0.2 on 2022-05-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_book_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
